dist: trusty
language: r
cache:
- packages
r:
- release
- devel
addons:
  sauce_connect:
    no_ssl_bump_domains: localhost
notifications:
  email: false
  slack:
    secure: gJWBgTlMkV1DsCgTaE2TLBfop/Zg/rSKhvUsNOrv67CsvR0V1oRdhBoXsBIgSL/z5LN8PF1WzRat9Q6YVOF8ePj1w6iluzhxbMOquzFZq/7glh/UGE07VPM4nBhWPP78mB4pAiY2PO85mySGqu5/OZRHrJxzyuTTt1vmdN8XRqkFVDx6/GwiqBZSrQZ/riZY2z5RGlZfhiGUcyszlDiRFSAineFEHH8pbTBs4uFjP63SiuHJPUIzoKe+edD7qmBJawU3Yq5ExC0Jt2cleSoABd5ATrT6SGSWePxJZ9/LeF9hLeCqxE/PjGLRMM6G/I8vnGg9I67RzP1Wl9oZ0WoFjS1yPP9PnsO8uxdPyj60OCWZmXj1uJopYVRPjZLdTXdoJnC7honIkn0g7IoE7vm5soeRUN1mgPRycF1BLqpZUN25BnOx9DOBSQBhzKP6Ob0+Eu0GBH4l7y28YNsXkWymQFDQOWOycUTO9KxeInvQQpb6lqKh86kjAJlwZmsbGKrU6gmfMDiaslp3gKU4P7HEr5eR6p5KVQKW428uEBEM+J6khXAj9lNLIQgX8eLiFARbpM/XFmc4/Go7J/D/Z4tcRHvxmWdGaEhKqeJoq9x7439VyvrZ8Tx3hUGksgTUKx7el0VcQGZ5fjyYO7PKWPAO8g9ldbYhBQ5lok9WYbpx3mI=
