language: r
sudo: required
services:
  - docker
env:
  global:
  - NOT_CRAN=true
  matrix:
  - suite=001
  - suite=002
  - suite=003
  - suite=004.01.1
  - suite=004.01.2
  - suite=004.02
  - suite=004.03.1
  - suite=004.03.2
  - suite=004.03.3
  - suite=004.04
  - suite=004.05
  - suite=004.06
  - suite=004.07
  - suite=004.08
cache:
- packages
r:
- release
r_github_packages:
  - johndharrison/binman
  - johndharrison/wdman
before_script:
  - docker pull selenium/standalone-firefox:3.141.59-palladium
  # Run selenium/firefox docker container. Pipe output to selenium_out.txt
  - docker run -v $TRAVIS_BUILD_DIR/inst/app:/data --network=host -v /dev/shm:/dev/shm selenium/standalone-firefox:3.141.59-palladium > selenium_out.txt 2>&1 &
  - |
    cd tests/testthat
    # Remove all test files not in current test suite
    ls | grep -P "^testSuite(?!$suite)" | xargs -d"\n" rm
    cd ../../
notifications:
  email: false
  slack:
    secure: gJWBgTlMkV1DsCgTaE2TLBfop/Zg/rSKhvUsNOrv67CsvR0V1oRdhBoXsBIgSL/z5LN8PF1WzRat9Q6YVOF8ePj1w6iluzhxbMOquzFZq/7glh/UGE07VPM4nBhWPP78mB4pAiY2PO85mySGqu5/OZRHrJxzyuTTt1vmdN8XRqkFVDx6/GwiqBZSrQZ/riZY2z5RGlZfhiGUcyszlDiRFSAineFEHH8pbTBs4uFjP63SiuHJPUIzoKe+edD7qmBJawU3Yq5ExC0Jt2cleSoABd5ATrT6SGSWePxJZ9/LeF9hLeCqxE/PjGLRMM6G/I8vnGg9I67RzP1Wl9oZ0WoFjS1yPP9PnsO8uxdPyj60OCWZmXj1uJopYVRPjZLdTXdoJnC7honIkn0g7IoE7vm5soeRUN1mgPRycF1BLqpZUN25BnOx9DOBSQBhzKP6Ob0+Eu0GBH4l7y28YNsXkWymQFDQOWOycUTO9KxeInvQQpb6lqKh86kjAJlwZmsbGKrU6gmfMDiaslp3gKU4P7HEr5eR6p5KVQKW428uEBEM+J6khXAj9lNLIQgX8eLiFARbpM/XFmc4/Go7J/D/Z4tcRHvxmWdGaEhKqeJoq9x7439VyvrZ8Tx3hUGksgTUKx7el0VcQGZ5fjyYO7PKWPAO8g9ldbYhBQ5lok9WYbpx3mI=
